package main

type AutoGenerated struct {
	Network struct {
		Version   int    `json:"version"`
		Renderer  string `json:"renderer"`
		Ethernets struct {
			Enp3S0 struct {
				Addresses   []string `json:"addresses"`
				Nameservers struct {
					Search    []string `json:"search"`
					Addresses []string `json:"addresses"`
				} `json:"nameservers"`
				Routes []struct {
					To  string `json:"to"`
					Via string `json:"via"`
				} `json:"routes"`
			} `json:"enp3s0"`
		} `json:"ethernets"`
	} `json:"network"`
}

type NetworkConfig struct {
	Version   int                       `json:"version"`
	Renderer  string                    `json:"renderer,omitempty"`
	Ethernets map[string]EthernetConfig `json:"ethernets"`
}

type EthernetConfig struct {
	Match       EthernetMatcher `json:"match"`
	Addresses   []string        `json:"addresses"`
	Gateway4    string          `json:"gateway4,omitempty"`
	Nameservers *Nameservers    `json:"nameservers,omitempty"`
	Routes      []Route         `json:"routes,omitempty"`
}

type EthernetMatcher struct {
	Macaddress string `json:"macaddress"`
}

type Nameservers struct {
	Addresses []string `json:"addresses"`
}

type Route struct {
	To  string `json:"to"`
	Via string `json:"via"`
}

////

type Metadata struct {
	InstanceID    string `json:"instance-id"`
	LocalHostname string `json:"local-hostname"`
}

////

type UserData struct {
	Users []User `json:"users"`
}

type User struct {
	Name              string   `json:"name"`
	PlainTextPasswd   string   `json:"plain_text_passwd"`
	Gecos             string   `json:"gecos,omitempty"`
	Shell             string   `json:"shell,omitempty"`
	Groups            string   `json:"groups,omitempty"`
	Sudo              string   `json:"sudo,omitempty"`
	SSHAuthorizedKeys []string `json:"ssh_authorized_keys,omitempty"`
}

///

type MMDSConfig struct {
	Latest LatestConfig `json:"latest"`
}

type LatestConfig struct {
	MetaData interface{} `json:"meta-data,omitempty"`
	UserData interface{} `json:"user-data,omitempty"`
}
